//tealium universal tag - utag.2 ut4.0.201506121436, Copyright 2015 Tealium.com Inc. All Rights Reserved.
if(utag.ut===undefined){utag.ut={};}
if(typeof utag.ut.loader==="undefined"){utag.ut.loader=function(o,a,b,c,l){a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){b.hFlag=0;b.onreadystatechange=function(){if((this.readyState==='complete'||this.readyState==='loaded')&&!b.hFlag){b.hFlag=1;o.cb();}};b.onload=function(){if(!b.hFlag){b.hFlag=1;o.cb();}};}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}
try{(function(id,loader){var u=utag.o[loader].sender[id]={};u.ev={'view':1,'link':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){u.data={"id":"690","sync":0,"dispType":"js","ptcl":document.location.protocol==="https:"?"https":"http","bsUrl":"bs.serving-sys.com/BurstingPipe","mobile":0,"activityParams":{},"retargetParams":{},"dynamicRetargetParams":{},"conditionalParams":{},"base_url":(document.location.protocol=="https:"?"https://secure-":"http://")+"ds.serving-sys.com/SemiCachedScripts/ebOneTag.js","order_id":"","product_ids":[],"product_quantities":[],"product_prices":[]};if(u.ev[a]||typeof u.ev.all!="undefined"){var c,d,e,f;c=[];window.versaTag={};for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f]=="id"||e[f]=="sync"||e[f]=="dispType"||e[f]=="ptcl"||e[f]=="bsUrl"||e[f]=="mobile"||e[f]=="activityParams"||e[f]=="retargetParams"||e[f]=="dynamicRetargetParams"||e[f]=="conditionalParams"||e[f]=="pageName"||e[f]=="orderId"||e[f]=="productId"||e[f]=="quantity"||e[f]=="RetargetingId"||e[f]=="target"){u.data[e[f]]=b[d];}else{u.data[e[f]]=b[d];versaTag[e[f]]=b[d];}}}}
u.data.order_id=u.data.orig||u.data.order_id||b._corder||"";if(u.data.product_ids.length===0&&b._cprod!==undefined){u.data.product_ids=b._cprod.slice(0);}
if(u.data.product_quantities.length===0&&b._cquan!==undefined){u.data.product_quantities=b._cquan.slice(0);}
u.data.activityParams.pageName=u.data.pageName;u.data.activityParams.OrderID=u.data.orderId||u.data.order_id;u.data.activityParams.productid=u.data.productId||u.data.product_ids.join("|");u.data.activityParams.productinfo=utag.data._cprodname.join("|");u.data.activityParams.Currency_Code=utag.data._ccurrency;u.data.activityParams.Value=utag.data._ctotal;u.data.activityParams.Quantity=u.data.quantity||u.data.product_quantities[0];u.data.retargetParams.RetargetingId=u.data.retargetParams.RetargetingId||u.data.RetargetingId;u.data.retargetParams.target=u.data.retargetParams.target||u.data.target;if(!u.initialized){u.initialized=true;versaTag.id=u.data.id;versaTag.sync=u.data.sync;versaTag.dispType=u.data.dispType;versaTag.ptcl=u.data.ptcl;versaTag.bsUrl=u.data.bsUrl;versaTag.mobile=u.data.mobile;versaTag.activityParams=u.data.activityParams;versaTag.retargetParams=u.data.retargetParams;versaTag.dynamicRetargetParams=u.data.dynamicRetargetParams;versaTag.conditionalParams=u.data.conditionalParams;utag.ut.loader({"type":"script","src":u.data.base_url,"cb":function(){},"loc":"script","id":"ebOneTagUrlId"});}else{if('view'===a){versaTagObj._oneTagObj.id=u.data.id||versaTagObj._oneTagObj.id;versaTagObj._oneTagObj.sync=u.data.sync||versaTagObj._oneTagObj.sync;versaTagObj._oneTagObj.dispType=u.data.dispType||ersaTagObj._oneTagObj.dispType;versaTagObj._oneTagObj.ptcl=u.data.ptcl||versaTagObj._oneTagObj.ptcl;versaTagObj._oneTagObj.bsUrl=u.data.bsUrl||versaTagObj._oneTagObj.bsUrl;versaTagObj._oneTagObj.mobile=u.data.mobile||versaTagObj._oneTagObj.mobile;}
if(u.data.activityParams){versaTagObj.clearActivityParam();for(d in u.data.activityParams){if(u.data.activityParams.hasOwnProperty(d)){versaTagObj.setActivityParam(d,u.data.activityParams[d]);}}}
if(u.data.retargetParams){versaTagObj.clearRetargetParam();for(d in u.data.retargetParams){if(u.data.retargetParams.hasOwnProperty(d)){versaTagObj.setRetargetParam(d,u.data.retargetParams[d]);}}}
if(u.data.conditionalParams){versaTagObj.clearConditionalParam();for(d in u.data.conditionalParams){if(u.data.conditionalParams.hasOwnProperty(d)){versaTagObj.setConditionParam(d,u.data.conditionalParams[d]);}}}
if('view'==a){versaTagObj.generateRequest(u.data['dom.url']);}else if('link'==a){versaTagObj.generateRequest(u.data.activityParams.pageName);}}}};utag.o[loader].loader.LOAD(id);})('2','diesel.main');}catch(e){}
